@startuml
    autonumber
    Client -> WebPage : enters card details
    WebPage -> Adyen : initiates BIN verification\nas shopperReference we'll use\na client`s username
    Adyen -> WebPage : responses with resultCode
    Client -> WebPage : trying to pay for something
    Server -> WebPage : returns a list of possible cards to pay, using shopperReference\nbut actual card info is reccuringDetailReference
    Client -> WebPage : confirms payment
    WebPage -> Server : sends payment data
    Server -> Adyen : sends reccurring payment request
    Adyen -> Server : response with code
@enduml