version: '3'

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
  web:
    build: .
    command: bash -c "python3 manage.py deploy db.json && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db