version: '3'

services:
  db:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - "5400:5432"
  redis:
    image: redis:3.2
    ports:
      - "6300:6379"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5800:8080"
    environment:
      - API_URL=http://generator.swagger.io/api/swagger.json