@startuml
class TemplateParty {
  String name
  Profile created_by
  State _state
  Integer frequency_id
}

class TemplateMembers {
  Integer profile_id
  Integer template_party_id
  Boolean is_owner
}

class TemplateMemberFoodExclude {
  Integer template_membership_id
  Integer ordered_food_id
}

class TemplateOrderedFood {
  Integer template_party_id
  String food_name
  Decimal price_per_unit
  Integer quantity
}

class CrontabSchedule {
  String name
  String hour
  String minute
  String day
  String month
  String day_of_week
}

TemplateParty "1" --* "many" TemplateMembers
TemplateMembers "1" --* "many" TemplateMemberFoodExclude
TemplateParty "1" --* "many" TemplateOrderedFood
TemplateOrderedFood "1" --* "many" TemplateMemberFoodExclude
TemplateParty "1" --* "many" CrontabSchedule
@enduml