# Generated by Django 2.0.5 on 2018-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0003_auto_20180531_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='legacy_id',
            field=models.IntegerField(null=True),
        ),
    ]
