# Generated by Django 2.0.5 on 2018-06-05 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0005_profile_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authModule.Code'),
        ),
    ]
