# Generated by Django 2.0.5 on 2018-05-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('total_sponsored', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='authModule.Profile')),
                ('members', models.ManyToManyField(related_name='memberships', through='party_calculator.Membership', to='authModule.Profile')),
                ('ordered_food', models.ManyToManyField(related_name='ordered_by', to='party_calculator.OrderedFood')),
            ],
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_calculator.Party'),
        ),
        migrations.AddField(
            model_name='membership',
            name='excluded_food',
            field=models.ManyToManyField(to='party_calculator.OrderedFood'),
        ),
        migrations.AddField(
            model_name='membership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_calculator.Party'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.Profile'),
        ),
    ]
