# Generated by Django 2.0.5 on 2018-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(related_name='members', through='party_calculator.Membership', to='authModule.Profile'),
        ),
    ]
