# Generated by Django 2.0.5 on 2018-06-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party_calculator_auth', '0001_initial'),
        ('party_calculator', '0001_initial'),
        ('django_celery_beat', '0006_auto_20180210_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateparty',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_calculator_auth.Profile'),
        ),
        migrations.AddField(
            model_name='templateparty',
            name='members',
            field=models.ManyToManyField(related_name='template_member_of', through='party_calculator.TemplateMembership', to='party_calculator_auth.Profile'),
        ),
        migrations.AddField(
            model_name='templateparty',
            name='ordered_food',
            field=models.ManyToManyField(related_name='template_order_of', to='party_calculator.TemplateOrderedFood'),
        ),
        migrations.AddField(
            model_name='templateparty',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.CrontabSchedule'),
        ),
        migrations.AddField(
            model_name='templateorderedfood',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_ordered_food', to='party_calculator.TemplateParty'),
        ),
        migrations.AddField(
            model_name='templatemembership',
            name='excluded_food',
            field=models.ManyToManyField(to='party_calculator.TemplateOrderedFood'),
        ),
        migrations.AddField(
            model_name='templatemembership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_memberships', to='party_calculator.TemplateParty'),
        ),
        migrations.AddField(
            model_name='templatemembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_calculator_auth.Profile'),
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_calculator_auth.Profile'),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(related_name='member_of', through='party_calculator.Membership', to='party_calculator_auth.Profile'),
        ),
        migrations.AddField(
            model_name='party',
            name='ordered_food',
            field=models.ManyToManyField(related_name='ordered_by', to='party_calculator.OrderedFood'),
        ),
        migrations.AddField(
            model_name='party',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='party_calculator.TemplateParty'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_calculator.Party'),
        ),
        migrations.AddField(
            model_name='membership',
            name='excluded_food',
            field=models.ManyToManyField(to='party_calculator.OrderedFood'),
        ),
        migrations.AddField(
            model_name='membership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='party_calculator.Party'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_calculator_auth.Profile'),
        ),
    ]
