# Generated by Django 2.0.5 on 2018-06-25 09:06

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    food = apps.get_model("party_calculator", "Food")

    food.objects.using(db_alias).bulk_create([
        food(name='beer_test', price=128.99),
        food(name='pizza_test', price=512),
        food(name='nuggets_test', price=256)
    ])

def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    food = apps.get_model("party_calculator", "Food")

    food_items = food.objects.using(db_alias)\
        .filter(name__in=['beer_test', 'pizza_test', 'nuggets_test'])

    for item in food_items:
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0002_auto_20180618_1230'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
