# Generated by Django 2.0.5 on 2018-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0003_test_food_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-is_owner']},
        ),
        migrations.AlterModelOptions(
            name='templatemembership',
            options={'ordering': ['-is_owner']},
        ),
    ]
