# Generated by Django 2.0.5 on 2018-05-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0003_auto_20180525_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='MemberExcludedFood',
            new_name='excluded_food',
        ),
    ]
