# Generated by Django 2.0.5 on 2018-05-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0004_auto_20180525_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='ordered_food',
            field=models.ManyToManyField(related_name='ordered_food', through='party_calculator.PartyDesiredFood', to='party_calculator.Food'),
        ),
    ]
