# Generated by Django 2.0.5 on 2018-07-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0004_auto_20180625_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('minute', models.CharField(default='*', max_length=240)),
                ('hour', models.CharField(default='*', max_length=96)),
                ('day_of_week', models.CharField(default='*', max_length=64)),
                ('day_of_month', models.CharField(default='*', max_length=124)),
                ('month_of_year', models.CharField(default='*', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='templateparty',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party_calculator.Schedule'),
        ),
    ]
