# Generated by Django 2.0.5 on 2018-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0005_auto_20180530_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydesiredfood',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
