# Generated by Django 2.0.5 on 2018-05-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0007_auto_20180530_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartyDesiredFood',
            new_name='OrderedFood',
        ),
    ]
