# Generated by Django 2.0.5 on 2018-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator', '0008_auto_20180530_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='excluded_food',
            field=models.ManyToManyField(to='party_calculator.OrderedFood'),
        ),
    ]
