# Generated by Django 2.0.5 on 2018-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoBigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_date_var', models.DateTimeField(auto_now=True)),
                ('some_int_var', models.IntegerField(null=True)),
                ('some_bool_var', models.BooleanField(default=False)),
                ('some_important_info', models.CharField(max_length=1024)),
            ],
        ),
    ]
