# Generated by Django 2.0.5 on 2018-06-19 14:51

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    pbm = apps.get_model("party_calculator_auth", "PseudoBigModel")
    psm_one = apps.get_model("party_calculator_auth", "PseudoSmallModel_One")
    psm_two = apps.get_model("party_calculator_auth", "PseudoSmallModel_Two")

    pbm_entries = pbm.objects.using(db_alias).all()
    for entry in pbm_entries:
        psmt_obj = psm_two.objects.using(db_alias).create(
            id=entry.id,
            some_date_var=entry.some_date_var,
            some_int_var=entry.some_int_var,
            some_bool_var=entry.some_bool_var
        )

        psm_one.objects.using(db_alias).create(
            psm_two=psmt_obj,
            some_important_info=entry.some_important_info
        )


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    pbm = apps.get_model("party_calculator_auth", "PseudoBigModel")
    psm_one = apps.get_model("party_calculator_auth", "PseudoSmallModel_One")
    psm_two = apps.get_model("party_calculator_auth", "PseudoSmallModel_Two")

    psmo_entries = psm_one.objects.using(db_alias).all()
    psmt_entries = psm_two.objects.using(db_alias).all()

    pbm.objects.using(db_alias).bulk_create([
        pbm(id=psmt_entry.id,
            some_date_var=psmt_entry.some_date_var,
            some_int_var=psmt_entry.some_int_var,
            some_bool_var=psmt_entry.some_bool_var,
            some_important_info=psmo_entry.some_important_info
        ) for psmo_entry, psmt_entry in zip(psmo_entries, psmt_entries)]
    )

    for psmo_entry, psmt_entry in zip(psmo_entries, psmt_entries):
        psmo_entry.delete()
        psmt_entry.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator_auth', '0002_pseudobigmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoSmallModel_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_date_var', models.DateTimeField(auto_now=True)),
                ('some_int_var', models.IntegerField(null=True)),
                ('some_bool_var', models.BooleanField(default=False))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PseudoSmallModel_One',
            fields=[
                ('psm_two', models.OneToOneField(to='party_calculator_auth.PseudoSmallModel_Two',
                                                 parent_link=True,
                                                 primary_key=True,
                                                 serialize=False,
                                                 on_delete=models.CASCADE)),
                ('some_important_info', models.CharField(max_length=1024, null=False, blank=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.DeleteModel(
            name='PseudoBigModel'
        )
    ]
