# Generated by Django 2.0.5 on 2018-06-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_calculator_auth', '0003_PseudoBigModel_into_PseudoSmallModels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudosmallmodel_one',
            name='psm_two',
        ),
        migrations.DeleteModel(
            name='PseudoSmallModel_One',
        ),
        migrations.DeleteModel(
            name='PseudoSmallModel_Two',
        ),
    ]
